-- MySQL Script generated by MySQL Workbench
-- 04/02/17 22:32:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tka_2017b
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tka_2017b
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tka_2017b` DEFAULT CHARACTER SET utf8 ;
USE `tka_2017b` ;

-- -----------------------------------------------------
-- Table `tka_2017b`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tka_2017b`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tka_2017b`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tka_2017b`.`student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_student_project_idx` (`project_id` ASC),
  CONSTRAINT `fk_student_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `tka_2017b`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
